### ISSUE TITLE
LinuxCNC -> grblHAL 

### ISSUE THREAD

**Issue by eecue** [kcjengr/probe_basic#63]
I'm interested in using you probe_basic for GrblHAL (https://github.com/grblHAL/core) instead of LinuxCNC.  Looking through the codebase I'm actually not quite sure where to start.  Can you point me in the right direction?

**Comment by KurtJacobson** [comment]
One of the intents of QtPyVCP (the framework used to build the ProbeBasic UI) is for it to be modular enough that it could be used with a "CNC control" other than LinuxCNC (I had GRBL in mind). The goal would be to abstract the interface with the control and make it pluggable. There has been a lot of work in this direction, and most of the communication with LinuxCNC is thru plugins, the main exception being the Actions. The problem is that there is still a good bit of code scattered about that relies on LinuxCNC being present.

I would start by unloading any LinuxCNC specific plugins (comment out in YAML file), and removing any references to linuxcnc and getting a bare GUI working, and then add back what is needed to communicate with grblHAL.

That is, unless you want to try to completely abstract the control interface.. This would be awesome, but a huge amount of work.

**Comment by eecue** [comment]
Thanks! Mind if I leave this open for further questions? I realize it’s not actually an issue

**Comment by eecue** [comment]
Closing this. Will make a new ticket to discuss things in the QtPyVCP
